name: agustinmazzinghi
favicon: null
layout_spectrum: 0.31287
typography_spectrum: 0.30277
title: Agustín Mazzinghi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161616'
    - '#a1a1a1'
    - '#ffffff'
    - '#8f0116'
    - '#3aad25'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
